networks:
  od16:
name: odoo
services:
  pg15:
    image: postgres:15
    hostname: pg15
    container_name: pg15
    restart: always
    stdin_open: true
    tty: true
    pull_policy: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - od16
    volumes:
      - postgres_15:/var/lib/postgresql/data/pgdata

  od16:
    image: odoo:16.0
    hostname: od16
    container_name: od16
    restart: always
    ports:
      - "80:8069"
    entrypoint: "odoo -c /etc/odoo/odoo.conf --dev=all"
    volumes:
      - ./odoo/oca:/mnt/oca
      - ./odoo/conf:/etc/odoo
      - ./odoo/enterprise:/mnt/enterprise
      - ./odoo/extra-addons:/mnt/extra-addons
    stdin_open: true
    tty: true
    pull_policy: always
    environment:
      - USER=odoo
      - PASSWORD=admin
    networks:
      - od16
    links:
      - pg15:db
    depends_on:
      - pg15

volumes:
  postgres_15: