networks:
  odoo-network:
    name: odoo-network
    driver: bridge

services:
  odoo:
    user: root
    image: odoo:${ODOO_VERSION}
    restart: always
    container_name: odoo-${ODOO_VERSION}
    hostname: odoo-${ODOO_VERSION}
    volumes:
      - C:/odoo-${ODOO_VERSION}:/var/lib/odoo
      - C:/odoo-${ODOO_VERSION}/conf:/etc/odoo/
      - C:/odoo-${ODOO_VERSION}/oca/:/mnt/oca/
      - C:/odoo-${ODOO_VERSION}/enterprise/:/mnt/enterprise/
      - C:/odoo-${ODOO_VERSION}/extra-addons/:/mnt/extra-addons/
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf --dev=all"
    networks:
      odoo-network:
    ports:
      - "80:8069"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 2048M
    environment:
      HOST: ${PASSWORD}  
      USER: ${USER}
      PASSWORD: ${PASSWORD}
    tty: true

  postgres:
    image: postgres:{POSTGRES_VERSION}
    restart: unless-stopped
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
      - PGDATA=/var/lib/postgresql/data/pgdata/ 
    volumes:
      - C:/postgres-${POSTGRES_VERSION}/data:/var/lib/postgresql/data/:rw
      - C:/postgres-${POSTGRES_VERSION}/initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      odoo-network:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 2048M