networks:
  odoo-network:

services:
  web:
    user: root
    image: odoo:${ODOO_VERSION}
    restart: always
    container_name: odoo-${ODOO_VERSION}
    hostname: odoo-${ODOO_VERSION}
    volumes:
      - ./odoo-${ODOO_VERSION}/oca:/mnt/oca/
      - ./odoo-${ODOO_VERSION}/conf:/etc/odoo/
      - ./odoo-${ODOO_VERSION}/odoo-data:/var/lib/odoo
      - ./odoo-${ODOO_VERSION}/enterprise:/mnt/enterprise/
      - ./odoo-${ODOO_VERSION}/extra-addons:/mnt/extra-addons/
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf --dev=all"
    networks:
      odoo-network:
    ports:
      - "8014:8069"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 2048M
    environment:
      HOST: postgres
      USER: odoo
      PASSWORD: admin
    tty: true
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    hostname: db
    container_name: db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata/ 
    volumes:
      - ./postgres-${POSTGRES_VERSION}/data:/var/lib/postgresql/data/
    networks:
      odoo-network:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 2048M
